### ISSUE TITLE
set_trace() cause exception

### ISSUE THREAD

**Issue by Grokzen** [jonathanslenders/ptpdb#3]
Found the following error when trying out this tool. Installed manually from source.

``` python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ptpdb import set_trace
>>> set_trace()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ptpdb/__init__.py", line 263, in set_trace
    PtPdb().set_trace(sys._getframe().f_back)
  File "ptpdb/__init__.py", line 124, in __init__
    PdbShortcutsToolbar(weakref.ref(self)),
TypeError: __init__() got an unexpected keyword argument '_extra_buffer_processors'
>>> 
```

**Comment by jonathanslenders** [comment]
This is because the latest ptpdb expects the latest ptpython. (And by latest, I mean the latest commit of the master branch on Github.) It doesn't work with the Pypi version yet. I will try to release new versions with bug fixes as fast as possible. (But quite busy lately.)

**Comment by Grokzen** [comment]
I am closing this because of what you said works by installing both libs from latest commit :]
